{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: market-api
  namespace: {{ include "cryptomarket.namespace" . }}
  labels:
    {{- include "cryptomarket.componentLabels" (dict "root" . "name" "market-api" "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: market-api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
