{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: market-api-secrets
  namespace: {{ include "cryptomarket.namespace" . }}
  labels:
    {{- include "cryptomarket.componentLabels" (dict "root" . "name" "market-api" "component" "api") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.ingestor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: market-ingestor-secrets
  namespace: {{ include "cryptomarket.namespace" . }}
  labels:
    {{- include "cryptomarket.componentLabels" (dict "root" . "name" "market-ingestor" "component" "ingestor") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.ingestor.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.realtime.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: realtime-gateway-secrets
  namespace: {{ include "cryptomarket.namespace" . }}
  labels:
    {{- include "cryptomarket.componentLabels" (dict "root" . "name" "realtime-gateway" "component" "realtime") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.realtime.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
